name: Análisis de Código con SonarCloud

on:
  push:
    branches:  
      - "master"
      - "main"  
  pull_request:
    branches:
      - "master"
      - "main"  

jobs:
  sonarCloudTrigger:
    name: Analizar Código con SonarCloud
    runs-on: ubuntu-latest
    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v3

      - name: Analizar con SonarCloud
        uses: sonarsource/sonarcloud-github-action@v1.3
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
